/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade2;

import java.util.ArrayList;

/**
 *
 * @author Isabella
 */
public final class Interface extends javax.swing.JFrame {

    ArrayList<Cachorro> listaCachorros;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();        
        Home home = new Home();
        listaCachorros = home.AdicionarListaCachorros();
        
        AjustarVisibilidadeFalse();
    }

    public void AjustarVisibilidadeFalse(){
        panelListaCachorros.setVisible(false);
        panelBuscarCachorro.setVisible(false);
        panelConferirLatido.setVisible(false);
        panelCachorroMaisVelho.setVisible(false);
        panelBrincar.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnConferirCachorros = new javax.swing.JButton();
        btnDadosCachorro = new javax.swing.JButton();
        btnConferirLatido = new javax.swing.JButton();
        btnCachorroVelho = new javax.swing.JButton();
        btnBrincar = new javax.swing.JButton();
        panelListaCachorros = new javax.swing.JPanel();
        scrollListarCachorros = new javax.swing.JScrollPane();
        lstCachorros = new javax.swing.JList<>();
        panelBuscarCachorro = new javax.swing.JPanel();
        btnBuscarCachorro = new javax.swing.JToggleButton();
        txtBuscarCachorro = new javax.swing.JTextField();
        lblBuscarCachorro = new javax.swing.JLabel();
        panelConferirLatido = new javax.swing.JPanel();
        btnVerLatido = new javax.swing.JToggleButton();
        txtConferirLatindo = new javax.swing.JTextField();
        lblConferirLatido = new javax.swing.JLabel();
        panelCachorroMaisVelho = new javax.swing.JPanel();
        lblCachorroMaisVelho = new javax.swing.JLabel();
        panelBrincar = new javax.swing.JPanel();
        btnBrincarCachorro = new javax.swing.JToggleButton();
        txtBrincar = new javax.swing.JTextField();
        lblBrincar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Cachorrinhos");

        btnConferirCachorros.setText("Listar Cachorros");
        btnConferirCachorros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConferirCachorrosMouseClicked(evt);
            }
        });
        btnConferirCachorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConferirCachorrosActionPerformed(evt);
            }
        });

        btnDadosCachorro.setText("Dados Cachorro");
        btnDadosCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadosCachorroActionPerformed(evt);
            }
        });

        btnConferirLatido.setText("Conferir Latido");
        btnConferirLatido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConferirLatidoActionPerformed(evt);
            }
        });

        btnCachorroVelho.setText("Cachorro Mais Velho");
        btnCachorroVelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCachorroVelhoActionPerformed(evt);
            }
        });

        btnBrincar.setText("Brincar");
        btnBrincar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrincarActionPerformed(evt);
            }
        });

        scrollListarCachorros.setViewportView(lstCachorros);

        javax.swing.GroupLayout panelListaCachorrosLayout = new javax.swing.GroupLayout(panelListaCachorros);
        panelListaCachorros.setLayout(panelListaCachorrosLayout);
        panelListaCachorrosLayout.setHorizontalGroup(
            panelListaCachorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaCachorrosLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(scrollListarCachorros, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListaCachorrosLayout.setVerticalGroup(
            panelListaCachorrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollListarCachorros, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );

        btnBuscarCachorro.setText("Procurar");
        btnBuscarCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCachorroActionPerformed(evt);
            }
        });

        txtBuscarCachorro.setText("Insira o nome do Cachorro para buscar");

        lblBuscarCachorro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarCachorro.setText(".");

        javax.swing.GroupLayout panelBuscarCachorroLayout = new javax.swing.GroupLayout(panelBuscarCachorro);
        panelBuscarCachorro.setLayout(panelBuscarCachorroLayout);
        panelBuscarCachorroLayout.setHorizontalGroup(
            panelBuscarCachorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarCachorroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscarCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCachorro)
                .addGap(81, 81, 81))
            .addGroup(panelBuscarCachorroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarCachorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBuscarCachorroLayout.setVerticalGroup(
            panelBuscarCachorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarCachorroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelBuscarCachorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCachorro)
                    .addComponent(txtBuscarCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblBuscarCachorro)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        btnVerLatido.setText("Procurar");
        btnVerLatido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLatidoActionPerformed(evt);
            }
        });

        txtConferirLatindo.setText("Insira o nome do Cachorro para buscar");

        lblConferirLatido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConferirLatido.setText(".");

        javax.swing.GroupLayout panelConferirLatidoLayout = new javax.swing.GroupLayout(panelConferirLatido);
        panelConferirLatido.setLayout(panelConferirLatidoLayout);
        panelConferirLatidoLayout.setHorizontalGroup(
            panelConferirLatidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConferirLatidoLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(txtConferirLatindo, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerLatido)
                .addGap(81, 81, 81))
            .addGroup(panelConferirLatidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConferirLatido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelConferirLatidoLayout.setVerticalGroup(
            panelConferirLatidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConferirLatidoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelConferirLatidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerLatido)
                    .addComponent(txtConferirLatindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblConferirLatido)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        lblCachorroMaisVelho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCachorroMaisVelho.setText(".");

        javax.swing.GroupLayout panelCachorroMaisVelhoLayout = new javax.swing.GroupLayout(panelCachorroMaisVelho);
        panelCachorroMaisVelho.setLayout(panelCachorroMaisVelhoLayout);
        panelCachorroMaisVelhoLayout.setHorizontalGroup(
            panelCachorroMaisVelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panelCachorroMaisVelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCachorroMaisVelhoLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(lblCachorroMaisVelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(5, 5, 5)))
        );
        panelCachorroMaisVelhoLayout.setVerticalGroup(
            panelCachorroMaisVelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(panelCachorroMaisVelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelCachorroMaisVelhoLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(lblCachorroMaisVelho)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnBrincarCachorro.setText("Brincar");
        btnBrincarCachorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrincarCachorroActionPerformed(evt);
            }
        });

        txtBrincar.setText("Insira o nome do Cachorro para brincar");

        lblBrincar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrincar.setText(".");

        javax.swing.GroupLayout panelBrincarLayout = new javax.swing.GroupLayout(panelBrincar);
        panelBrincar.setLayout(panelBrincarLayout);
        panelBrincarLayout.setHorizontalGroup(
            panelBrincarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBrincarLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(txtBrincar, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrincarCachorro)
                .addGap(81, 81, 81))
            .addGroup(panelBrincarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBrincar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBrincarLayout.setVerticalGroup(
            panelBrincarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBrincarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelBrincarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrincarCachorro)
                    .addComponent(txtBrincar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblBrincar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelConferirLatido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(178, 178, 178)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelListaCachorros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnConferirCachorros)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDadosCachorro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnConferirLatido)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCachorroVelho)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBrincar))
                                .addComponent(panelBuscarCachorro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelCachorroMaisVelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBrincar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConferirCachorros)
                    .addComponent(btnDadosCachorro)
                    .addComponent(btnConferirLatido)
                    .addComponent(btnCachorroVelho)
                    .addComponent(btnBrincar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListaCachorros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBuscarCachorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConferirLatido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCachorroMaisVelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBrincar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConferirCachorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferirCachorrosActionPerformed
        // TODO add your handling code here:
        AjustarVisibilidadeFalse();
        panelListaCachorros.setVisible(true);
        
        Home home = new Home();
        
        String [] Teste = {"<html>" + home.ExibirListaCachorros(listaCachorros) + "</html>"};
        lstCachorros.setListData(Teste); 

    }//GEN-LAST:event_btnConferirCachorrosActionPerformed

    private void btnConferirCachorrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConferirCachorrosMouseClicked
        // TODO add your handling code here:       
    }//GEN-LAST:event_btnConferirCachorrosMouseClicked

    private void btnBuscarCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCachorroActionPerformed
        // TODO add your handling code here:
        Home home = new Home();      
        lblBuscarCachorro.setText("<html>" + home.VerificarDados(txtBuscarCachorro.getText(), listaCachorros) + "</html>");
    }//GEN-LAST:event_btnBuscarCachorroActionPerformed

    private void btnDadosCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadosCachorroActionPerformed
        // TODO add your handling code here:
        AjustarVisibilidadeFalse();
        panelBuscarCachorro.setVisible(true);
        lblBuscarCachorro.setText("");
        txtConferirLatindo.setText("Insira o nome do Cachorro para buscar");
    }//GEN-LAST:event_btnDadosCachorroActionPerformed

    private void btnVerLatidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLatidoActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        lblConferirLatido.setText(home.Latir(txtConferirLatindo.getText(), listaCachorros));
    }//GEN-LAST:event_btnVerLatidoActionPerformed

    private void btnConferirLatidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConferirLatidoActionPerformed
        // TODO add your handling code here:
        AjustarVisibilidadeFalse();
        panelConferirLatido.setVisible(true);
        lblConferirLatido.setText("");
        txtBuscarCachorro.setText("Insira o nome do Cachorro para buscar");
    }//GEN-LAST:event_btnConferirLatidoActionPerformed

    private void btnCachorroVelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCachorroVelhoActionPerformed
        // TODO add your handling code here:
        AjustarVisibilidadeFalse();
        panelCachorroMaisVelho.setVisible(true);
        Home home = new Home();
        lblCachorroMaisVelho.setText(home.VerificaCachorroMaisVelho(listaCachorros));
    }//GEN-LAST:event_btnCachorroVelhoActionPerformed

    private void btnBrincarCachorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrincarCachorroActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        lblBrincar.setText(home.Brincar(txtBrincar.getText(), listaCachorros));
    }//GEN-LAST:event_btnBrincarCachorroActionPerformed

    private void btnBrincarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrincarActionPerformed
        // TODO add your handling code here:
        AjustarVisibilidadeFalse();
        panelBrincar.setVisible(true);
        txtBrincar.setText("Insira o nome do Cachorro para buscar");
        lblBrincar.setText("");
    }//GEN-LAST:event_btnBrincarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrincar;
    private javax.swing.JToggleButton btnBrincarCachorro;
    private javax.swing.JToggleButton btnBuscarCachorro;
    private javax.swing.JButton btnCachorroVelho;
    private javax.swing.JButton btnConferirCachorros;
    private javax.swing.JButton btnConferirLatido;
    private javax.swing.JButton btnDadosCachorro;
    private javax.swing.JToggleButton btnVerLatido;
    private javax.swing.JLabel lblBrincar;
    private javax.swing.JLabel lblBuscarCachorro;
    private javax.swing.JLabel lblCachorroMaisVelho;
    private javax.swing.JLabel lblConferirLatido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstCachorros;
    private javax.swing.JPanel panelBrincar;
    private javax.swing.JPanel panelBuscarCachorro;
    private javax.swing.JPanel panelCachorroMaisVelho;
    private javax.swing.JPanel panelConferirLatido;
    private javax.swing.JPanel panelListaCachorros;
    private javax.swing.JScrollPane scrollListarCachorros;
    private javax.swing.JTextField txtBrincar;
    private javax.swing.JTextField txtBuscarCachorro;
    private javax.swing.JTextField txtConferirLatindo;
    // End of variables declaration//GEN-END:variables
}
